"""Init

Revision ID: 6cabb41d8c0b
Revises: b0c9b60a8c33
Create Date: 2024-08-22 20:31:46.512302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cabb41d8c0b'
down_revision: Union[str, None] = 'b0c9b60a8c33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('quote_author_fkey', 'quote', type_='foreignkey')
    op.create_foreign_key(None, 'quote', 'author', ['author'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quote', type_='foreignkey')
    op.create_foreign_key('quote_author_fkey', 'quote', 'author', ['author'], ['id'])
    # ### end Alembic commands ###
