"""Init

Revision ID: bf7bcf447c76
Revises: e96cc14d4a29
Create Date: 2024-08-23 14:03:29.037440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf7bcf447c76'
down_revision: Union[str, None] = 'e96cc14d4a29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quote', 'author',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('quote_author_fkey', 'quote', type_='foreignkey')
    op.create_foreign_key(None, 'quote', 'author', ['author'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quote', type_='foreignkey')
    op.create_foreign_key('quote_author_fkey', 'quote', 'author', ['author'], ['id'])
    op.alter_column('quote', 'author',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
